diff_drive_controller: add realtime_tools dependency
When executing 'catkin_make -DCATKIN_ENABLE_TESTING=0', this error occurs:

In file included from [...]/diff_drive_controller/src/diff_drive_controller.cpp:45:0:
[...]/diff_drive_controller/include/diff_drive_controller/diff_drive_controller.h:46:44: fatal error: realtime_tools/realtime_buffer.h: No such file or directory
 #include <realtime_tools/realtime_buffer.h>
                                            ^
compilation terminated.
make[2]: *** [ros_controllers/diff_drive_controller/CMakeFiles/diff_drive_controller.dir/src/diff_drive_controller.cpp.o] Error 1

Obviously, the realtime_tools dependency was missing in the CMakeLists.txt file.

Conflicts:

	diff_drive_controller/CMakeLists.txt